USE shop;
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name varchar(35) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP)
ENGINE=ARCHIVE;
